### ISSUE TITLE
Update NuGet with Unified iOS support 

### ISSUE THREAD

**Issue by jamesmontemagno** [dmanning23/AdMobBuddy#1]
Hey there! With 1.3.1 now on stable with Unified support it would be great if you could update the plugin with this support. I created a short How To video on how to do this: https://www.youtube.com/watch?v=nF8DbL-PVKw

**Comment by dmanning23** [comment]
Hi James! Thanks for getting in touch. Yeah, the WinPhone version of this library works beautifully, install the package and two lines of code and boom, ads on the screen.  Unfortunately as of Friday I don't have access to the required hardware & software to continue work on the Android & iOS versions :(

If I get the Xamarin open-source license I can probably finish the Android library, but until I can line up the required hardware the iOS part is going to have to go on hiatus. 

I'd love to keep working on this, other developers seem really interested in it. The Nuget package description has a big "WIP, does not work", but it's been installed over 80 times in the last week anyway.

Also if you know anyone that's hiring, I start the job hunt on Monday & I'd really appreciate any help :)

Cheers!
-Dan

**Comment by jamesmontemagno** [comment]
Dan,

You should be able to apply for the open source license. Let me know if you need a link for that.

I should be able to test out the iOS bits for you as well.

I would recommend removing your current packages and publishing on that is a pre-release. it is really easy to do: http://docs.nuget.org/docs/reference/versioning  

This way people don't think it is finished and that it is under development.

Also, we have a new jobs listing forum: http://forums.xamarin.com/categories/job-listings  if you haven't seen that check it out and best of luck.

Best,
James

**Comment by valdetero** [comment]
@jamesmontemagno @dmanning23 I have added a pull request for ios unified.
