### ISSUE TITLE
Banner ads not working

### ISSUE THREAD

**Issue by fzdravko** [dmanning23/AdMobBuddy#10]
In monogame banner ads not working.
It gives error at start:

System.MissingMethodException
  Message=Method not found: Android.Gms.Ads.AdSize Android.Gms.Ads.AdSize.GetCurrentOrientationAnchoredAdaptiveBannerAdSize(Android.Content.Context,int)

**Comment by dmanning23** [comment]
This should be working now... Updated the Android library to use the latest AdMob packages.
