### ISSUE TITLE
Not sure if I am using it correctly.

### ISSUE THREAD

**Issue by rlingineni** [dmanning23/AdMobBuddy#4]
Hi,

So I've implemented it as such in my XAML.CS page:

`AdMobBuddyControl ad = new AdMobBuddyControl ()
{AdUnitId = "pub-************************", };`

I then added that view to my stacklayout `main` as `main.Children.Add(ad);`

Am I doing the right implementation. I can't see any ad, I have deployed it to my iOS device as the release version because I read somewhere admob won't work on the simulator. I am not at all familiar with this stuff, so let me know if I need to add something. Please excuse me if I am missing something basic.

**Comment by dmanning23** [comment]
If you are using the Nuget package, it won't work on iOS. Some devs have had success by building it from source. I will probably start working on the AdMobBuddy again here in the near future.

**Comment by rlingineni** [comment]
Oh ok, I was trying to make it work on iOS. Thank you, I will use it in my android application.

**Comment by dmanning23** [comment]
I'm pretty sure the Android nuget package doesn't work either :(
I know the WinPhone package is good.

**Comment by rlingineni** [comment]
Aww man :(
