### ISSUE TITLE
Migrate from old deprecated Xamarin Components

### ISSUE THREAD

**Issue by MagnusJohansson** [dmanning23/AdMobBuddy#5]
Hi,
there is a dependency on the old, deprecated Xamarin.GooglePlayServices.
Could you please update to use the new [Xamarin.GooglePlayServices.Ads](https://components.xamarin.com/view/googleplayservices-ads) ?

Thanks.

EDIT: This on the latest public  [NuGet package ](https://www.nuget.org/packages/Xam.Plugins.Forms.AdMobBuddy/), v1.0.6

**Comment by dmanning23** [comment]
I'm cleaning out these old Issues, the GooglePlayServices has been updated to .Ads
