### ISSUE TITLE
Why not support NETStandard

### ISSUE THREAD

**Issue by h1138289016** [dmanning23/AdMobBuddy#7]
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	NU1701	已使用“.NETFramework,Version=v4.6.1”而不是项目目标框架“.NETStandard,Version=v2.0”还原包“AdMobBuddy 1.0.24”。此包可能与项目不完全兼容。	App2	E:\VSWindowForms\App2\App2\App2\App2.csproj	1

**Comment by dmanning23** [comment]
AdMob is only for Android & iOS, the Windows package is just a shim for testing purposes.
