### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by Egehanozsoy** [dmanning23/AdMobBuddy#8]
Java.Lang.NoClassDefFoundError: 'Failed resolution of: Lcom/google/android/gms/dynamic/zzp;'

while executing this line of code
ads = new AdMobAdapter(this,...

i left insterstitial as " " because i dont have one yet

**Comment by dmanning23** [comment]
Looks like it is not handling the case where ad ids are empty.
I should have a fix up soon, thanks for reporting this error!

**Comment by dmanning23** [comment]
Ok, if you update the nuget package it should work now.
Cheers!
